[package]
name = "goal_consumer"
version = "0.1.0"
authors = ["Ship <michael.shiplet@vivint.com>"]
edition = "2018"

[dependencies]
lapin-futures = "0.14.0"
bson = "0.12.2"
mongodb = "0.3.10"
tokio = "0.1.6"
futures = "0.1.25"
serde_json = "1.0"
chrono = "0.4"
time = "0.1.40"